# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/build-aspnetapp/WeatherService/Dockerfile'
        tags: |
          $(tag)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AZU-TEST-ENV-AKSHAY'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name "ACRTestEnvAkshay"
          az acr run --registry ACRTestEnvAkshay -f build-push-hello-world.yaml https://github.com/Azure-Samples/acr-tasks.git
          